# vim:ts=2:sw=2:et
language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

env:
  - SMARTY="2.6.*"
  - SMARTY="3.1.*"

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

before_install:
  - sudo apt-get update && travis_retry sudo apt-get --reinstall install -qq language-pack-{et,pl}
  - dpkg --list | grep language-pack
  - locale -a
  # enable EZC for hhvm
  - cat /etc/hhvm/php.ini
  - echo hhvm.enable_zend_compat=true | sudo tee -a /etc/hhvm/php.ini

install:
  - composer install --no-interaction --prefer-source

before_script:
  - make -C tests/i18n

script:
  - composer require --dev smarty/smarty=$SMARTY
  - phpunit
